config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'collections#index'
  
  get 'about'     => 'static_pages#about'
  get 'privacy'   => 'static_pages#privacy'
  get 'terms'     => 'static_pages#terms'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :reviews, only: [:index, :show]
    put :favorite, on: :member
    put :add_to_collection, on: :member
    collection do
      get 'popular'
      get 'latest'
      get 'quick'
      get 'admin_view'
    end
  end
  resources :reviews, only: [:create, :update, :destroy]
  resources :collections do
    put :remove_from_collection, on: :member
    collection do
      get 'admin_view'
    end
  end

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_and_belongs_to_many :recipes
  belongs_to :user, counter_cache: true
  
  mount_uploader :image, ImageUploader
  
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 130 }
  validates :description, allow_blank: true, length: { maximum: 1000 }
  validates :featured, inclusion: { in: [true, false] }
  validate :image_size
  
  private
  
    # Validates size of an uploaded image
    def image_size
      if image.size > 5.megabytes
        errors.add(:image, "should be less than 5MB")
      end
    end
    
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include RecipesHelper
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :admin_view, :remove_from_collection]
  before_action :admin_user, only: [:new, :create, :edit, :update, :destroy, :admin_view, :remove_from_collection]
  
  def index
    @collections = Collection.where(featured: true)
    @recipe = Recipe.popular.order("RANDOM()").first
    @category = Recipe::CATEGORY_OPTIONS.sample
    @category_recipes = Recipe.category(@category).not_private.sort_by("Rating").limit(3)
    @cuisine = Recipe::CUISINE_OPTIONS.sample
    @cuisine_recipes = Recipe.cuisine(@cuisine).not_private.sort_by("Rating").limit(3)
    @course = Recipe::COURSE_OPTIONS.sample
    @course_recipes = Recipe.course(@course).not_private.sort_by("Rating").limit(3)
  end
  
  def show
    @collection = Collection.find(params[:id])
    @recipes = @collection.recipes.paginate(page: params[:page])
  end
  
  def new
    @collection = Collection.new
  end

  def create
    @collection = current_user.collections.build(collection_params)
    if @collection.save
      flash[:success] = "Collection created - add recipes"
      redirect_to admin_view_recipes_path
    else
      render 'new'
    end
  end
  
  def edit
    @collection = Collection.find(params[:id])
  end
  
  def update
    @collection = Collection.find(params[:id])
    if @collection.update_attributes(collection_params)
      flash[:success] = "Collection updated"
      redirect_to admin_view_collections_path
    else
      render 'edit'
    end
  end
  
  def destroy
    Collection.find(params[:id]).destroy
    flash[:success] = "Collection deleted"
    redirect_to request.referrer || admin_view_collections_path
  end
  
  def admin_view
    @collections = Collection.paginate(page: params[:page])
  end
  
  def remove_from_collection
    @collection = Collection.find(params[:id])
    @recipe = Recipe.find(params[:recipe])
    if in_collection?(@collection, @recipe)
      @collection.recipes.delete(@recipe)
      flash[:success] = "Removed from Collection"
      redirect_to edit_collection_path(@collection)
    else
      flash[:danger] = "Error removing Recipe from Collection"
      redirect_to edit_collection_path(@collection)
    end
  end
  
  private
  
    def collection_params
      params.require(:collection).permit(:name, :description, :featured, :image, :remove_image)
    end
  
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_admin_collection.html.erb
<tr>
  <td><%= link_to image_tag(collection.image.url, size: "32", alt: collection.name), collection %></td>
  <td><%= link_to collection.id, collection %></td>
  <td><%= link_to collection.name, collection %></td>
  <td><%= collection.recipes.size %></td>
  <td><%= "✔" if collection.featured == true %></td>
  <td><%= collection.updated_at.strftime("%m-%d-%Y") %></td>
  <td><%= link_to "Edit", edit_collection_path(collection), class: "btn btn-primary btn-sm", role: "button" %></td>
  <td><%= link_to "Delete", collection, method: :delete, class: "btn btn-danger btn-sm", role: "button", data: { confirm: "Are you sure you want to delete this collection?" } %></td>
</tr>

app/views/collections/admin_view.html.erb
<% provide(:title, "Collection Admin Panel") %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h2>All Collections &nbsp; <%= link_to "New", new_collection_path, class: "btn btn-primary", role: "button" %></h2></div>
      <div class="table-responsive">
        <table id="collection-list" class="table table-hover">
          <thead>
            <tr>
              <th>IMAGE</th>
              <th>ID</th>
              <th>NAME</th>
              <th>RECIPES</th>
              <th>FEATURED</th>
              <th>UPDATED</th>
              <th><!-- empty header for "Edit" button --></th>
              <th><!-- empty header for "Delete" button --></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: 'admin_collection', collection: @collections, as: :collection %>
          </tbody>
        </table>
      </div><!-- /.table-responsive -->
    </div> <!-- /.panel.panel-default -->
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= will_paginate @rcollections, inner_window: 1, renderer: BootstrapPagination::Rails %>
      </div><!-- /.col-xs-12 -->
    </div><!--/.row -->
  </div><!-- /.col-md-12 -->
</div> <!-- /.row -->

app/views/collections/edit.html.erb
<% provide(:title, "Edit #{@collection.name}") %>

<div class="row">
  <div class="col-md-12">
    <h1>Edit <%= @collection.name %> Collection</h1>
  </div>
</div>

<hr/>

<div class="row">
  <div class="col-md-12">
      <div class="table-responsive">
        <table id="recipe-list" class="table table-hover">
          <thead>
            <tr>
              <th>IMAGE</th>
              <th>ID</th>
              <th>TITLE</th>
              <th>AUTHOR</th>
              <th>TIME</th>
              <th>RATING</th>
              <th>CUSINE</th>
              <th>CATEGORY</th>
              <th>COURSE</th>
              <th>CREATED</th>
              <th><!-- empty header for "View" button --></th>
              <th><!-- empty header for "Remove" button --></th>
            </tr>
          </thead>
          <tbody>
            <% @collection.recipes.each do |recipe| %>
              <tr>
                <td><%= image_tag(recipe.image_url.url, size: "32", alt: recipe.title) %></td>
                <td><%= recipe.id %></td>
                <td><%= link_to recipe.title, recipe %></td>
                <td><%= link_to recipe.user.name, recipe.user %></td>
                <td><%= recipe.total_time %></td>
                <td><%= recipe.average_rating %></td>
                <td><%= recipe.cuisine %></td>
                <td><%= recipe.category %></td>
                <td><%= recipe.course %></td>
                <td><%= recipe.created_at.strftime("%m-%d-%Y") %></td>
                <td><%= link_to "View", recipe, :class => "btn btn-primary btn-sm", :role => "button" %></td>
                <td><%= link_to "Remove", remove_from_collection_collection_path(@collection, :recipe => recipe.id), :method => "put", :class => "btn btn-danger btn-sm", :role => "button" %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.table-responsive -->
  </div><!-- /.col-md-12 -->
</div> <!-- /.row -->

<%= form_for(@collection, html: { mulitpart: true }) do |f| %>
<div class="row">
  <div class="col-md-12">
    <%= render 'shared/error_messages', object: f.object %>
    <div class="main-img-wrapper">
      <%= image_tag(@collection.image.url, alt: @collection.name, class: "img") %>
      <div id="img-update-fields">
        <%= f.label :image, "Collection Image (5MB or less)" %>
        <%= f.file_field :image, class: 'form-control', accept: 'image/jpeg,image/gif,image/png' %>
        <%= f.label :remove_image, class: "checkbox inline" do %>
          <%= f.check_box :remove_image %>
          <span>Remove Current Image (press save to remove)</span>
        <% end %>
      </div>
    </div><!-- /.main-img-wrapper -->
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div id="recipe-panel" class="panel panel-info center-block">
          <div class="panel-heading">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control', value: @collection.name %>
            </div><!-- /.form-group -->
          </div><!-- /.panel-heading -->
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-12">
                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description, class: 'form-control', value: @collection.description %>
                </div><!-- /.form-group -->
              </div><!-- /.col-xs-12 -->
            </div><!-- /.row -->
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= f.label :featured, class: "checkbox inline" do %>
                  <%= f.check_box :featured, value: @collection.featured %>
                  <span>Featured (listed on home page)</span>
                <% end %>
                <%= f.submit "Update", class: 'create-button btn btn-primary' %>
              </div>
            </div><!-- /.row -->
          </div><!-- /.panel-body -->
        </div><!-- /.panel -->
      </div><!-- /.col-md-8 -->
    </div><!-- /.row -->
  </div><!-- /.col-md-12" -->
</div><!-- /.row -->

<% end %><!-- /form -->

app/views/collections/index.html.erb
<% provide(:title, "Home") %>

<div class="row">
  <div class="col-sm-8">
      <div id="intro" class="jumbotron">
        <h1>Welcome to MakeChow!</h1>
        <p>Store, share, and rate recipes. Save your favorites.</p>
        <% if logged_in? %>
          <p><%= link_to "Your Recipes", user_path(current_user, anchor: "user-recipes"), :class => "btn btn-primary btn-lg", :role => "button" %></p>
        <% else %>
          <p><%= link_to "Sign Up Now!", signup_path, :class => "btn btn-primary btn-lg", :role => "button" %></p>
        <% end %>
      </div> <!-- /.jumbotron -->
  </div><!-- /.col-sm-8 -->
  <div class="col-sm-4">
    <% if !@recipe.nil? %>
      <div id="featured-recipe">
        <h3 class="text-center"><%= link_to "Chow now!", @recipe %></h3>
        <%= render @recipe %>
      </div><!-- /#featured-recipe -->
    <% end %>
  </div><!-- /.col-sm-4 -->
</div><!-- /.row -->

<div class="row">
  <% if @category_recipes.any? %>
    <div class="col-sm-12 col-md-9" id="featured-category">
      <div class="well">
        <div class="row">
          <div class="col-md-12 col-sm-6 col-lg-3">
            <div class="panel panel-default">
              <h3><%= link_to "#{@category} chow", { controller: "recipes", action: "index", category: @category, sort_by: "Date" } %></h3>
              <%= link_to image_tag("category.png", size: 128), { controller: "recipes", action: "index", category: @category, sort_by: "Date" } %>
            </div><!-- /.panel -->
          </div><!-- /.col-md-12 -->
          <% @category_recipes.each do |recipe| %>
            <div class="col-md-4 col-sm-6 col-lg-3">
              <%= render partial: 'recipes/recipe', object: recipe %>
            </div><!-- /.col-md-4 -->
          <% end %>
        </div><!-- /.row -->
      </div><!-- /.well -->
    </div><!-- /#featured-category -->
  <% end %>
  <% if @collections.any? %>
    <div class="col-sm-12 col-md-3 featured-collection">
      <%= link_to @collections[0], class: "thumbnail" do %>
        <%= image_tag(@collections[0].image.url(:square), alt: @collections[0].name) %>
        <div class="overlay">
          <div class="collection-content">
            <p><%= @collections[0].description %></p>
            <h2><%= @collections[0].name %></h2>
            <p class="small"><%= pluralize(@collections[0].recipes.size, "recipe", "recipes") %></p>
          </div><!-- /.collection-content -->
        </div><!-- /.overlay -->
      <% end %>
    </div><!-- /.featured-collection -->
  <% end %>
</div><!-- /.row -->


<div class="row">
  <% if @collections.size > 1 %>
    <div class="col-sm-12 col-md-3 featured-collection">
      <%= link_to @collections[1], class: "thumbnail" do %>
        <%= image_tag(@collections[1].image.url(:square), alt: @collections[1].name) %>
        <div class="overlay">
          <div class="collection-content">
            <p><%= @collections[1].description %></p>
            <h2><%= @collections[1].name %></h2>
            <p class="small"><%= pluralize(@collections[1].recipes.size, "recipe", "recipes") %></p>
          </div><!-- /.collection-content -->
        </div><!-- /.overlay -->
      <% end %>
    </div><!-- /.featured-collection -->
  <% else %>
    <div class="col-md-3"></div>
  <% end %>
  <% if @cuisine_recipes.any? %>
    <div class="col-sm-12 col-md-9" id="featured-cuisine">
      <div class="well">
        <div class="row">
          <div class="col-md-12 col-sm-6 col-lg-3 visible-sm visible-xs visible-md">
            <div class="panel panel-default">
              <h3><%= link_to "#{@cuisine} chow", { controller: "recipes", action: "index", cuisine: @cuisine, sort_by: "Date" } %></h3>
              <%= link_to image_tag("cuisine.png", size: 128), { controller: "recipes", action: "index", cuisine: @cuisine, sort_by: "Date" } %>
            </div><!-- /.panel -->
          </div><!-- /.col-sm-12 -->
          <% @cuisine_recipes.each do |recipe| %>
            <div class="col-md-4 col-sm-6 col-lg-3">
              <%= render partial: 'recipes/recipe', object: recipe %>
            </div><!-- /.col-md-4 -->
          <% end %>
          <div class="col-md-12 col-sm-6 col-lg-3 hidden-sm hidden-xs hidden-md">
            <div class="panel panel-default">
              <h3><%= link_to "#{@cuisine} chow", { controller: "recipes", action: "index", cuisine: @cuisine, sort_by: "Date" } %></h3>
              <%= link_to image_tag("cuisine.png", size: 128), { controller: "recipes", action: "index", cuisine: @cuisine, sort_by: "Date" } %>
            </div><!-- /.panel -->
          </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
      </div><!-- /.well -->
    </div><!-- /#featured-cuisine -->
  <% end %>
</div><!-- /.row -->

<div class="row">
  <% if @course_recipes.any? %>
    <div class="col-sm-12 col-md-9" id="featured-course">
      <div class="well">
        <div class="row">
          <div class="col-md-12 col-sm-6 col-lg-3">
            <div class="panel panel-default">
              <h3><%= link_to "#{@course.pluralize(2)}", { controller: "recipes", action: "index", course: @course, sort_by: "Date" } %></h3>
              <%= link_to image_tag("course.png", size: 128), { controller: "recipes", action: "index", course: @course, sort_by: "Date" } %>
            </div><!-- /.panel -->
          </div><!-- /.col-md-12 -->
          <% @course_recipes.each do |recipe| %>
            <div class="col-md-4 col-sm-6 col-lg-3">
              <%= render partial: 'recipes/recipe', object: recipe %>
            </div><!-- /.col-md-4 -->
          <% end %>
        </div><!-- /.row -->
      </div><!-- /.well -->
    </div><!-- /#featured-course -->
  <% end %>
  <% if @collections.size > 2 %>
    <div class="col-sm-12 col-md-3 featured-collection">
      <%= link_to @collections[2], class: "thumbnail" do %>
        <%= image_tag(@collections[2].image.url(:square), alt: @collections[2].name) %>
        <div class="overlay">
          <div class="collection-content">
            <p><%= @collections[2].description %></p>
            <h2><%= @collections[2].name %></h2>
            <p class="small"><%= pluralize(@collections[2].recipes.size, "recipe", "recipes") %></p>
          </div><!-- /.collection-content -->
        </div><!-- /.overlay -->
      <% end %>
    </div><!-- /.featured-collection-->
  <% end %>
</div><!-- /.row -->

<div class="row">
  <div class="col-xs-12">
    <div class="well adspace" style="min-height: 200px; width: 100%;">
      <p>AD SPACE HERE</p>
    </div>
  </div><!-- /.col-xs-12 -->
</div><!-- /.row -->

app/views/collections/new.html.erb
<% provide(:title, "New Collection") %>

<div class="row">
  <div class="col-md-12">
    <h1>New Collection</h1>
  </div>
</div>

<hr/>

<%= form_for(@collection, html: { mulitpart: true }) do |f| %>
<div class="row">
  <div class="col-md-12">
    <%= render 'shared/error_messages', object: f.object %>
    <div class="main-img-wrapper">
      <%= image_tag(@collection.image.url, alt: @collection.name, class: "img") %>
      <div id="img-update-fields">
        <%= f.label :image, "Collection Image (5MB or less)" %>
        <%= f.file_field :image, class: 'form-control', accept: 'image/jpeg,image/gif,image/png' %>
      </div>
    </div><!-- /.main-img-wrapper -->
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div id="recipe-panel" class="panel panel-info center-block">
          <div class="panel-heading">
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div><!-- /.form-group -->
          </div><!-- /.panel-heading -->
          <div class="panel-body">
            <div class="row">
              <div class="col-xs-12">
                <div class="form-group">
                  <%= f.label :description %>
                  <%= f.text_area :description, class: 'form-control' %>
                </div><!-- /.form-group -->
              </div><!-- /.col-xs-12 -->
            </div><!-- /.row -->
            <div class="row">
              <div class="col-md-6 col-md-offset-3">
                <%= f.label :featured, class: "checkbox inline" do %>
                  <%= f.check_box :featured %>
                  <span>Featured (listed on home page)</span>
                <% end %>
                <%= f.submit "Create", class: 'create-button btn btn-primary' %>
              </div>
            </div><!-- /.row -->
          </div><!-- /.panel-body -->
        </div><!-- /.panel -->
      </div><!-- /.col-md-8 -->
    </div><!-- /.row -->
  </div><!-- /.col-md-12" -->
</div><!-- /.row -->
<% end %><!-- /form -->

app/views/collections/show.html.erb
<% provide(:title, @collection.name) %>

<div class="row">
  <div class="col-sm-6">
    <div class="page-header">
      <h1><%= @collection.name %></h1>
      <p><%= @collection.description %></p>  
    </div><!-- /.page-header -->
  </div><!-- /.col-sm-6 -->
  <div class="col-sm-6">
    <div class="well adspace" style="min-height: 100px; width: 100%">
      <p>AD SPACE HERE</p>
    </div>
  </div><!-- /.col-sm-6 -->
</div><!-- /.row -->


<div class="row collection-recipes">
  <% if @recipes.count == 0 %>
    <div class="col-md-12">
      <h3>No recipes in <%= @collection.name %></h3>
    </div>
  <% else %>
    <%= render @recipes %>
  <% end %>
</div> <!-- /.row -->

<div class="row text-center">
  <div class="col-xs-12">
    <%= will_paginate @recipes, inner_window: 1, renderer: BootstrapPagination::Rails %>
  </div>
</div>