config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'collections#index'
  
  get 'about'     => 'static_pages#about'
  get 'privacy'   => 'static_pages#privacy'
  get 'terms'     => 'static_pages#terms'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :reviews, only: [:index, :show]
    put :favorite, on: :member
    put :add_to_collection, on: :member
    collection do
      get 'popular'
      get 'latest'
      get 'quick'
      get 'admin_view'
    end
  end
  resources :reviews, only: [:create, :update, :destroy]
  resources :collections do
    put :remove_from_collection, on: :member
    collection do
      get 'admin_view'
    end
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :collections
  has_many :reviews, dependent: :destroy
  has_many :steps, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  
  # Users that have favorited
  has_many :favorite_recipes
  has_many :favorited_by, through: :favorite_recipes, source: :user, dependent: :destroy
  
  accepts_nested_attributes_for :steps, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
  
  mount_uploader :image_url, ImageUploader
  before_save :set_total_time

  scope :popular, -> { where(["average_rating >= :average_rating", average_rating: "3.5"]).not_private }
  scope :latest, -> { where(["created_at > :created_at", created_at: 5.days.ago]).not_private }
  scope :quick, -> { where(["total_time <= :total_time", total_time: "30"]).not_private }
  scope :not_private, -> { where.not(hidden: true) }
  scope :sort_by, ->(symbol) do
    case symbol
      when "Rating"
        order average_rating: :desc
      when "Date"
        order created_at: :desc 
      when "Time to Make"
        order total_time: :asc
    end
  end
  scope :category, ->(category) { where(category: category) }
  scope :cuisine, ->(cuisine) { where(cuisine: cuisine) }
  scope :course, ->(course) { where(course: course) }
  
  CATEGORY_OPTIONS = ["Breakfast", "Brunch", "Lunch", "Dinner"]
  COURSE_OPTIONS = ["Appetizer", "Beverage", "Bread", "Dessert", "Finger food", "Main dish", "Salad", "Side dish", "Snack", "Soup and stew"]
  CUISINE_OPTIONS = ["American", "Argentine", "Australian", "Brazilian", "Canadian", "Caribbean", "Central American", "Chinese", "English", "Ethiopian", "French", "German", "Greek", "Indian", "Irish", "Italian", "Jewish", "Korean", "Mexican", "Moroccan", "Native American", "Persian", "Polish", "Portuguese", "Russian", "Scandinavian", "South Pacific", "Spanish", "Thai", "Turkish", "Vietnamese"]
  SORTING_OPTIONS = ["Date", "Rating", "Time to Make" ]

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 130 }
  validates :description, presence: true
  validates :prep_time, presence: true, numericality: { only_integer: true, greater_than: -1 }
  validates :cook_time, presence: true, numericality: { only_ingeter: true, greater_than: -1 }
  validates :servings, presence: true, length: { maximum: 80 }
  validates :hidden, inclusion: { in: [true, false] }
  validate :image_size
  validates :category, presence: true, inclusion: { in: CATEGORY_OPTIONS }
  validates :course, presence: true, inclusion: { in: COURSE_OPTIONS }
  validates :cuisine, presence: true, inclusion: { in: CUISINE_OPTIONS }
  validates :average_rating, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  
  def self.search(value)
    if value
      if Rails.env.production?
        where(['(title ILIKE :search_term OR description ILIKE :search_term)', search_term: "%" + value + "%" ]).not_private
      else
        where(['(title LIKE :search_term OR description LIKE :search_term OR id LIKE :search_term)', search_term: "%" + value + "%" ]).not_private
      end
    else
      not_private
    end
  end
  
  private
  
    # Validates size of an uploaded image
    def image_size
      if image_url.size > 5.megabytes
        errors.add(:image_url, "should be less than 5MB")
      end
    end
    
    def set_total_time
      self.total_time = prep_time + cook_time
    end
    
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  include RecipesHelper
  before_action :logged_in_user, only: [:new, :create, :edit, :update, :destroy, :favorite, :admin_view, :add_to_collection]
  before_action :recipe_owner, only: [:edit, :update, :destroy]
  before_action :hidden_recipe, only: [:show]
  before_action :admin_user, only: [:admin_view, :add_to_collection]
  
  def index
    @recipes = Recipe.search(params[:search]).paginate(page: params[:page], per_page: 12)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
  end
  
  def show
    @recipe = Recipe.find(params[:id])
    @steps = @recipe.steps.all
    @ingredients = @recipe.ingredients.all
    @reviews = @recipe.reviews.limit(6)
    if logged_in?
      @review = current_user.reviews.find_by(recipe_id: params[:id]) || current_user.reviews.build
    end
  end
  
  def new
    @recipe = Recipe.new
    @recipe.steps.build(step_number: 0) # needed to display form field
    @recipe.ingredients.build # needed to display form field
  end
  
  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:success] = "Recipe created!"
      redirect_to @recipe
    else
      render 'new'
    end
  end
  
  def edit 
    @recipe = Recipe.find(params[:id])
    @recipe.steps.build(step_number: 0) if @recipe.steps.empty? # need at least one instance to display form field
    @recipe.ingredients.build if @recipe.ingredients.empty? # need at least one instance to display form field
  end
  
  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(recipe_params)
      flash[:success] = "Recipe updated"
      redirect_to @recipe
    else
      render 'edit'
    end
  end
  
  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = "Recipe deleted"
    redirect_to request.referrer || current_user
  end
  
  def favorite
    @recipe = Recipe.find(params[:id])
    if existing_favorite?(@recipe)
      current_user.favorites.delete(@recipe)
      flash[:success] = "Removed from Favorites"
      redirect_to @recipe
    else
      current_user.favorites << @recipe
      flash[:success] = "Saved to Favorites"
      redirect_to @recipe 
    end
  end
  
  def popular
    @recipes = Recipe.popular.paginate(page: params[:page], per_page: 12)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
  end
  
  def latest
    @recipes = Recipe.latest.paginate(page: params[:page], per_page: 12)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
  end
  
  def quick
    @recipes = Recipe.quick.paginate(page: params[:page], per_page: 12)
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
  end
  
  def admin_view
    @recipes = Recipe.search(params[:admin_search]).paginate(page: params[:page])
    @collections = Collection.all
    filtering_params(params).each do |key, value|
      @recipes = @recipes.public_send(key, value) if value.present?
    end
  end
  
  def add_to_collection
    @collection = Collection.find_by(id: params[:collection])
    @recipe = Recipe.find(params[:id])
    if params[:collection].blank?
      flash[:warning] = "No Collection Supplied - Remove Recipes from Collections on the Edit Collection Screen"
      redirect_to admin_view_recipes_path
    elsif in_collection?(@collection, @recipe)
      flash[:warning] = "Already in the Collection"
      redirect_to admin_view_recipes_path
    else
      @collection.recipes << @recipe
      flash[:success] = "Added to Collection"
      redirect_to admin_view_recipes_path
    end
  end
  
  private
  
    def recipe_params
      params.require(:recipe).permit(:title, :description, :cook_time, :prep_time, :image_url, :remove_image_url, :servings, :hidden, :cuisine, :course,:category, :average_rating, steps_attributes: [:id, :step_number, :content, :_destroy], ingredients_attributes: [:id, :name, :quantity, :_destroy])
    end
    
    def filtering_params(params)
      params.slice(:category, :cuisine, :course, :sort_by)
    end
    
    def recipe_owner
      recipe = current_user.recipes.find_by(id: params[:id])
      unless current_user.admin?
        if recipe.nil?
          flash[:danger] = "Cannot modify another users recipes"
          redirect_to root_url
        end
      end
    end
    
    def hidden_recipe
      recipe = Recipe.find(params[:id])
      unless logged_in? && (recipe.user_id == current_user.id)
        if recipe.hidden == true
          flash[:danger] = "This recipe is private"
          redirect_to root_url
        end
      end
    end
  
end

app/helpers/recipes_helper.rb
module RecipesHelper
  
  # Returns true if the current user has already favorited the recipe
  def existing_favorite?(recipe)
    !current_user.favorites.find_by(id: recipe.id).nil?
  end 
  
  # Return true if the recipe is already in the collection
  def in_collection?(collection, recipe)
    !collection.recipes.find_by(id: recipe.id).nil?
  end
  
  # Returns the given integer as a string formatted as hrs/mins
  def hours_and_minutes(number)
    hours = number/60 == 0 ? nil : pluralize(number/60, "hr", "hrs")
    minutes = number%60 == 0 ? nil : pluralize(number%60, "min", "mins")
    if hours && minutes
      hours + " " + minutes
    elsif hours
      hours
    elsif minutes
      minutes
    else
      ""
    end
  end
  
end

app/views/recipes/_favorite.html.erb
<div class="col-sm-3" id="recipe-<%= favorite.id %>">
  <div class="thumbnail">
  <%= link_to(favorite) do %>
    <div class="thumb-img">
      <%= image_tag(favorite.image_url.url, alt: favorite.title, class: "img") if favorite.image_url? %>
    </div>
    <div class="caption">
      <h3><%= favorite.title %></h3>
      <% if favorite.description.length < 71 %>
        <p><%= favorite.description %></p>
      <% else %>
        <p><%= favorite.description[0...70].concat("...") %></p>
      <% end %>
    </div> <!-- /.caption -->
  <% end %>
  <% if logged_in? %>
    <% if (favorite.user_id == current_user.id) %>
      <div class="recipe-buttons text-right">
        <%= link_to "Edit", edit_recipe_path(favorite.id), class: "btn btn-primary btn-sm", role: "button" %>
        <%= link_to "Delete", recipe, method: :delete, class: "btn btn-danger btn-sm", role: "button", data: { confirm: "Are you sure you want to delete this recipe?" } %>
      </div> <!-- /.recipe-buttons -->
     <% end %>
  <% end %>
  </div> <!-- /.thumbnail -->
</div> <!-- /.col-sm-3 -->

app/views/recipes/_index_footer.html.erb
<div class="row user-recipes">
  <% if @recipes.count == 0 %>
    <div class="col-md-12">
      <h3>No Recipes Found</h3>
    </div>
  <% else %>
    <%= render @recipes %>
  <% end %>
</div> <!-- /.row -->

<div class="row text-center">
  <div class="col-xs-12">
    <%= will_paginate @recipes, inner_window: 1, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/recipes/_index_header.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="page-header text-center">
      <% if params[:search].nil? %>
        <h1>Browse</h1>
        <ul class="nav nav-pills center-pills">
          <li role="presentation" class="<%= 'active' if current_page?(action: 'index') %>"><%= link_to "All", { action: "index", sort_by: "Date"} %></li>
          <li role="presentation" class="<%= 'active' if current_page?(action: 'popular') %>"><%= link_to "Popular", { action: "popular", sort_by: "Date"} %></li>
          <li role="presentation" class="<%= 'active' if current_page?(action: 'latest') %>"><%= link_to "Recent", { action: "latest", sort_by: "Date"} %></li>
          <li role="presentation" class="<%= 'active' if current_page?(action: 'quick') %>"><%= link_to "Quick", { action: "quick", sort_by: "Date"} %></li>
        </ul>
      <% else %>
        <h1><%= @recipes.size %> results for: <small><%= params[:search] %></small></h1>
      <% end %>
    </div><!-- /.page-header -->
  </div><!-- /.col-sm-12 -->
</div><!-- /.row -->

app/views/recipes/_ingredient_fields.html.erb
<div class="form-group">
  <div class="row">
    <div class="ingredient-wrapper clearfix">
      <div class="col-xs-3">
        <%= f.text_field :quantity, class: 'form-control' %>
      </div><!-- /.col-xs-3 -->
      <div class="col-xs-7">
        <%= f.text_field :name, class: 'form-control' %>
      </div><!-- /.col-xs-7 -->
      <div class="col-xs-2">
        <%= link_to_remove_association f, { wrapper_class: "form-group" } do %>
          <%= button_tag type: 'button', class: 'delete-button btn btn-sm btn-danger' do %>
            <span class='glyphicon glyphicon-remove' aria-hidden='true'></span>
          <% end %>
        <% end %>
      </div><!-- /.col-xs-2 -->
    </div><!-- /.ingredient-wrapper -->
  </div><!-- /.row -->
</div><!-- /.form-group -->

app/views/recipes/_recipe.html.erb
<% if current_page?(root_path) %>
  <div id="recipe-<%= recipe.id %>">
<% else %>
<div class="col-sm-4 col-md-3" id="recipe-<%= recipe.id %>">
<% end %>
  <div class="thumbnail">
  <%= link_to(recipe) do %>
    <div class="thumb-img">
      <%= image_tag(recipe.image_url.url(:square), alt: recipe.title, class: "img") %>
      <div class="recipe-head">
        <h3><%= recipe.title %></h3>
      </div> <!-- /.recipe-head -->
      <div class="overlay">
        <% if recipe.description.length < 101 %>
          <p><%= recipe.description %></p>
        <% else %>
          <p><%= recipe.description[0..100].concat("...") %></p>
        <% end %>
        <p>created: <%= recipe.created_at.strftime("%b %d, %Y") %></p>
      </div><!-- /.overlay -->
    </div><!-- /.thumb-img -->
  <% end %>
    <div class="caption text-center">
      <%= link_to(image_tag(recipe.user.image_url.url(:square), size: "48", alt: recipe.user.name, class: "img"), recipe.user) %>
      <% if logged_in? && current_user?(recipe.user) %>
        <div class="recipe-buttons">
          <%= link_to "Edit", edit_recipe_path(recipe.id), class: "btn btn-primary btn-sm", role: "button" %>
          <%= link_to "Delete", recipe, method: :delete, class: "btn btn-danger btn-sm", role: "button", data: { confirm: "Are you sure you want to delete this recipe?" } %>
        </div> <!-- /.recipe-buttons -->
      <% else %>
        <p class="author">by: <%= link_to(recipe.user.name, recipe.user) %></p>
      <% end %>
      <div class="rating-display recipe-rating">
        <p class="hidden-xs">(<%= recipe.reviews.size %>)</p>
        <% case recipe.average_rating %>
        <% when 4.5..5 %>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
        <% when 3.5...4.5 %>
          <span></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
        <% when 2.5...3.5 %>
          <span></span>
          <span></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
        <% when 1.5...2.5 %>
          <span></span>
          <span></span>
          <span></span>
          <span class="filled-star"></span>
          <span class="filled-star"></span>
        <% when 0.1...1.5 %>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span class="filled-star"></span>
        <% else %>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        <% end %>
        <p class="visible-xs">(<%= recipe.reviews.size %>)</p>
      </div><!-- /.rating-display -->
      <div class="recipe-time">
        <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
        <%= hours_and_minutes(recipe.total_time) %>
      </div>
      <% if recipe.hidden == true %>
        <span class="private-lock glyphicon glyphicon-lock"></span>
      <% end %>
    </div><!-- /.caption -->
  </div> <!-- /.thumbnail -->
</div> <!-- /.col-sm-3 -->

app/views/recipes/admin_view.html.erb
<% provide(:title, 'Recipe Admin') %>

<div class="row">
  <div class="col-sm-12">
    <div class="page-header text-center">
      <% if params[:admin_search].nil? %>
        <h1>All Recipes</h1>
      <% else %>
        <h1><%= @recipes.size %> results for: <small><%= params[:admin_search] %></small></h1>
      <% end %>
    </div><!-- /.page-header -->
  </div><!-- /.col-sm-12 -->
</div><!-- /.row -->

<div class="row">
  <%= form_tag admin_view_recipes_path, :method => 'get', role: 'search' do %>
    <div class="form-group">
      <div class="col-xs-10 col-md-4 col-md-offset-4">
        <%= text_field_tag :admin_search, params[:admin_search], class: 'form-control', placeholder: 'Search' %>
      </div>
      <div class="col-xs-2">
        <%= button_tag(type: 'submit', class: 'btn btn-default', name: nil) do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<%= render 'recipes/filters' %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="table-responsive">
        <table id="admin-recipe-list" class="table table-hover">
          <thead>
            <tr>
              <th>ID</th>
              <th>TITLE</th>
              <th>AUTHOR</th>
              <th>TIME</th>
              <th>RATING</th>
              <th>CUSINE</th>
              <th>CATEGORY</th>
              <th>COURSE</th>
              <th>CREATED</th>
              <th>COLLECTIONS</th>
              <th>SELECT COLLECTION</th>
            </tr>
          </thead>
          <tbody>
            <% @recipes.each do |recipe| %>
              <tr>
                <td><%= recipe.id %></td>
                <td><%= link_to(recipe.title, recipe) %></td>
                <td><%= link_to(recipe.user.name, recipe.user) %></td>
                <td><%= recipe.total_time %></td>
                <td><%= recipe.average_rating %></td>
                <td><%= recipe.cuisine %></td>
                <td><%= recipe.category %></td>
                <td><%= recipe.course %></td>
                <td><%= recipe.created_at.strftime("%m-%d-%Y") %></td>
                <td>
                  <% if recipe.collections.any? %>
                    <% recipe.collections.each do |collection| %>
                      <%= link_to(collection.name, edit_collection_path(collection)) + " | " %>
                    <% end %>
                  <% end %>
                </td>
                <td>
                  <%= form_tag add_to_collection_recipe_path(recipe), :method => 'put', role: 'form' do %>
                    <%= select_tag(:collection, options_for_select(@collections.collect{|cn| [cn.name, cn.id]}, (recipe.collections.first.id if recipe.collections.any?)), { class: 'form-control', include_blank: true }) %>
                    <%= submit_tag("Add", :name => nil, class: 'btn btn-primary btn-small') %>
                  <% end %>
                </td>
            <% end %>
          </tbody>
        </table>
      </div><!-- /.table-responsive -->
    </div> <!-- /.panel.panel-default -->
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= will_paginate @recipes, inner_window: 1, renderer: BootstrapPagination::Rails %>
      </div><!-- /.col-xs-12 -->
    </div><!--/.row -->
  </div><!-- /.col-md-12 -->
</div> <!-- /.row -->

app/views/recipes/show.html.erb
<% provide(:title, @recipe.title + " by " + @recipe.user.name) %>

<div class="row">
  <div class="col-md-8">
    <div class="main-img-wrapper">
      <%= image_tag(@recipe.image_url.url, alt: @recipe.title, class: "img") %>
      <div id="favorite-recipe">
        <% if logged_in? && existing_favorite?(@recipe) %>
          <%= link_to favorite_recipe_path(@recipe), class: "btn btn-default btn-lg favorited", role: "button", method: :put do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          <% end %>
        <% else %>
          <%= link_to favorite_recipe_path(@recipe), class: "btn btn-default btn-lg", role: "button", method: :put do %>
            <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
          <% end %>
        <% end %>
      </div><!-- /#favorite-recipe -->
      <% if @recipe.hidden == true %>
        <div id="private-recipe-tag">
          <h3><span class="label label-danger">Private</span></h3>
        </div><!-- /#private-recipe-tag -->
      <% end %>
    </div><!-- /.main-img-wrapper -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div id="recipe-panel" class="panel panel-info center-block">
          <div class="panel-heading">
            <h1 class="panel-title"><%= @recipe.title %></h1>
            <% if logged_in? && (@recipe.user_id == current_user.id || current_user.admin?) %>
              <div class="recipe-buttons">
                <%= link_to "Edit", edit_recipe_path, class: "btn btn-primary btn-sm", role: "button" %>
                <%= link_to "Delete", @recipe, method: :delete, class: "btn btn-danger btn-sm", role: "button", data: { confirm: "Are you sure you want to delete this recipe?" } %>
              </div> <!-- /.recipe-buttons -->
            <% else %>
              <h3>by: &nbsp;
                <%= link_to @recipe.user do %>
                  <%= image_tag(@recipe.user.image_url.url, size: "32", alt: @recipe.user.name, class: "img profile-img") %>
                  <%= @recipe.user.name %>
                <% end %>
              </h3>
            <% end %>
          </div><!-- /.panel-heading -->
          <div class="panel-body">
            <div class="row">
              <div class="col-sm-6">
                <p>Prep time: <%= hours_and_minutes(@recipe.prep_time) %></p>
                <p>Cook time: <%= hours_and_minutes(@recipe.cook_time) %></p>
              </div>
              <div class="col-sm-6">
                <h3>Total time: <%= hours_and_minutes(@recipe.total_time) %></h3>
              </div>
            </div><!-- /.row -->
            <div class="row">
              <div class="col-sm-6">
                <h4><span>Servings:</span> <%= @recipe.servings %></h4>
              </div><!-- /.col-xs-6 -->
              <div class="col-sm-6">
                <div class="well well-sm">
                  <div class="rating-display">
                    <p class="hidden-xs">(<%= @recipe.reviews.size %>)</p>
                    <% case @recipe.average_rating %>
                    <% when 4.5..5 %>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                    <% when 3.5...4.5 %>
                      <span></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                    <% when 2.5...3.5 %>
                      <span></span>
                      <span></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                    <% when 1.5...2.5 %>
                      <span></span>
                      <span></span>
                      <span></span>
                      <span class="filled-star"></span>
                      <span class="filled-star"></span>
                    <% when 0.1...1.5 %>
                      <span></span>
                      <span></span>
                      <span></span>
                      <span></span>
                      <span class="filled-star"></span>
                    <% else %>
                      <span></span>
                      <span></span>
                      <span></span>
                      <span></span>
                      <span></span>
                    <% end %>
                    <p class="visible-xs">(<%= @recipe.reviews.size %>)</p>
                  </div><!-- /.rating-display -->
                </div><!-- /.well -->
              </div><!-- /.col-xs-6 -->
            </div><!-- /.row -->
          </div><!-- /.panel-body -->
        </div><!-- /.panel -->
        <div id="category-info" class="well well-sm text-center">
          <div class="row">
            <div class="col-xs-4">Category: <%= @recipe.category %></div>
            <div class="col-xs-4">Cuisine: <%= @recipe.cuisine %></div>
            <div class="col-xs-4">Course: <%= @recipe.course %></div>
          </div><!-- /.row -->
        </div><!-- /.well -->
      </div><!-- /.col-md-10 -->
    </div><!-- /.row -->
  </div><!-- /.col-md-8" -->
  <div class="col-md-4">
    <div class="well adspace" style="min-height: 500px; width: 100%;">
      <p>AD SPACE HERE</p>
    </div>
  </div><!-- /.col-md-4 -->
</div><!-- /.row -->

<div class="row">
  <div class="col-md-8">
    <h3>Description:</h3>
    <p class="lead"><%= @recipe.description %></p>
  </div><!-- /.col-md-8 --> 
</div><!-- /.row -->
    
<div class="row">
  <div class="col-md-4 col-md-push-8">
    <h3>Ingredients:</h3>
    <% if @recipe.ingredients.any? %>
      <ul class="ingredients list-group">
        <%= render @ingredients %>
      </ul>
    <% else %>
      <h4>No ingredients provided</h4>
    <% end %>
  </div><!-- /.col-md-4 -->
  <div class="col-md-8 col-md-pull-4">    
    <h3>Directions:</h3>
    <% if @recipe.steps.any? %>
      <ol class="steps">
        <%= render @steps %>
      </ol>
    <% else %>
      <h4>No instructions provided</h4>
    <% end %>
  </div><!-- /.col-md-8 -->
</div><!-- /.row -->

<hr />

<div class="row">
  <div class="col-md-12">
    <h2>Reviews &nbsp;<span class="small"><%= link_to "view all", recipe_reviews_path(@recipe) %></span></h2>
    <% if @recipe.reviews.any? %>
      <div class="row">
        <%= render @reviews %>
      </div><!-- /.row -->
    <% else %>
      <div class="row">
        <div class="col-md-12">
          <p>No reviews yet.</p>
        </div><!-- /.col-md-12 -->
      </div><!-- /.row -->
    <% end %>
  </div><!-- /.col-md-12 -->
</div><!-- /.row -->

<div class="row">
  <div class="col-sm-12">
    <% if logged_in? && review_exists?(@recipe) %>
      <h4>Change your review:</h4>
    <% else %>
      <h4>Leave a review:</h4>
    <% end %>
  </div><!-- /.col-sm-12 -->
</div><!-- ./row -->

 
<div class="row">
  <div class="col-sm-6">
    <% if logged_in? %> 
      <div class="well">
        <%= render 'reviews/review_form' %>
      </div><!-- /.well -->
    <% else %>
      <%= link_to "Log in to leave a review", login_path, :class => "btn btn-primary", :role => "button" %>
    <% end %>
  </div><!-- /.col-sm-6 -->
  <div class="col-sm-6">
    <div class="well adspace" style="min-height: 300px; width: 100%;">
      <p>AD SPACE HERE</p>
    </div>
  </div><!-- /.col-sm-6 -->
</div><!-- /.row -->