config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'collections#index'
  
  get 'about'     => 'static_pages#about'
  get 'privacy'   => 'static_pages#privacy'
  get 'terms'     => 'static_pages#terms'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :reviews, only: [:index, :show]
    put :favorite, on: :member
    put :add_to_collection, on: :member
    collection do
      get 'popular'
      get 'latest'
      get 'quick'
      get 'admin_view'
    end
  end
  resources :reviews, only: [:create, :update, :destroy]
  resources :collections do
    put :remove_from_collection, on: :member
    collection do
      get 'admin_view'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  
  has_many :recipes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :collections, dependent: :destroy
  
  # Favorite recipes
  has_many :favorite_recipes
  has_many :favorites, through: :favorite_recipes, source: :recipe, dependent: :destroy
 
  mount_uploader :image_url, ImageUploader
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
 # not needed? VALID_URL_REGEX = /(\A|\s)((https?:\/\/)?[\w-]+(\.[\w-]+)+\.?(:\d+)?(\/\S*)?)/i
  validates :name, presence: true, length: { maximum: 100 }
  validates :email, presence: true, length: { maximum: 200 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  validates :location, allow_blank: true, length: { maximum: 200 }
  validate :image_size
  
  # Returns the hash digest of the given string
  def self.digest(string) 
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Remembers a user in the database for use in persistent sessions
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end
  
  # Forgets a user
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  # Activates an account
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end
  
  # Sends activation email
  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end
  
  # Sets the password reset attributes
  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end
  
  # Sends password reset email
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  # Returns true if a password reset has expired
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end
  
  private
  
    # Converts email to all lower case
    def downcase_email
      self.email = email.downcase
    end
    
    # Creates and assigns the activation token and digest
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
    
    # Validates size of an uploaded image
    def image_size
      if image_url.size > 5.megabytes
        errors.add(:image_url, "should be less than 5MB")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    unless @user.activated? || current_user.admin?
      redirect_to root_url and return
    end
    if logged_in? && current_user?(@user)
      @recipes = @user.recipes.order(created_at: :desc).paginate(page: params[:recipe_page], per_page: 8)
    else
      @recipes = @user.recipes.where.not(hidden: true).order(created_at: :desc).paginate(page: params[:recipe_page], per_page: 8)
    end
    @reviews = @user.reviews.order(created_at: :desc).paginate(page: params[:review_page], per_page: 6)
    @favorites = @user.favorites.order(created_at: :desc).paginate(page: params[:favorite_page], per_page: 8)
    @creation_date = @user.created_at.strftime("%Y")
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update 
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :location, :image_url, :remove_image_url)
    end
    
    # Confirms the correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<% if user.admin? && user.activated? %>
  <tr class="admin-row">
<% elsif !user.activated? %>
  <tr class="unactivated-row">
<% else %>
  <tr>
<% end %>
    <td><%= image_tag(user.image_url.url(:square), size: "32", alt: user.name) if user.image_url %></td>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.created_at.strftime("%m-%d-%Y") %></td>
    <td><%= link_to "View Profile", user, class: "btn btn-primary btn-sm", role: "button" %></td>
    <td><%= link_to "Delete User", user, method: :delete, class: "btn btn-danger btn-sm", role: "button", data: { confirm: "Are you sure you want to delete this user?" } %></td>
  </tr>

app/views/users/_user_favorite_display.html.erb
<div class="row user-favorites">
  <h2 class="text-center"><%= @user.name %>'s Favorited Recipes</h2>
  <% if @user.favorites.any? %>
  <%= render @favorites %>
  <% end %>
</div> <!-- /.row -->

<% if @user.favorites.any? %>
  <div class="row text-center">
    <div class="col-md-12">
      <%= will_paginate @favorites, param_name: 'favorite_page', inner_window: 1, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>

app/views/users/_user_recipe_display.html.erb
<div class="row user-recipes">
  <h2 class="text-center"><%= @user.name %>'s Recipes</h2>
    <% if current_user?(@user) %>
      <p class="text-center"><%= link_to "Create a new recipe", new_recipe_path, :class => "btn btn-primary btn-lg", :role => "button" %></p>
    <% end %>
  <% if @user.recipes.any? %>
  <%= render @recipes %>
  <% end %>
</div> <!-- /.row -->

<% if @user.recipes.any? %>
  <div class="row text-center">
    <div class="col-md-12">
      <%= will_paginate @recipes, param_name: 'recipe_page', inner_window: 1, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>

app/views/users/_user_review_display.html.erb
<div class="row user-reviews">
  <h2 class="text-center"><%= @user.name %>'s Reviews</h2>
  <% if @user.reviews.any? %>
  <%= render @reviews %>
  <% end %>
</div> <!-- /.row -->

<% if @user.reviews.any? %>
  <div class="row text-center">
    <div class="col-md-12">
      <%= will_paginate @reviews, param_name: 'review_page', inner_window: 1, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile of " + @user.name) %>

<div class="row">
  <h1 class="text-center">UPDATE YOUR PROFILE</h1>
</div>

<div class="row">
  <%= form_for(@user, html: { mulitpart: true }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="col-md-4">
       <%= image_tag( @user.image_url.url(:square), alt: @user.name + " Profile Image", class: "img-responsive center-block profile-img") %>
       <%= f.label :remove_image_url, class: "checkbox inline" do %>
          <%= f.check_box :remove_image_url %>
          <span>Remove Current Image (press save to remove)</span>
        <% end %>
       <%= f.label :image_url, "Profile Image URL (5MB or less)" %>
       <%= f.file_field :image_url, class: 'form-control', accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    <div class="col-md-8">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', :value => @user.name %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control', :value => @user.email %>
      
      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control', :value => @user.location %>
      
      <%= f.label :password, "New Password" %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirm New Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    </div>
  <% end %>
</div> <!-- /.row -->

app/views/users/index.html.erb
<% provide(:title, "All Users") %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading"><h2>All Users</h2></div>
      <div class="table-responsive">
        <table id="user-list" class="table table-hover">
          <thead>
            <tr>
              <td class="admin-row" colspan="2">admin</td>
              <td class="unactivated-row">not activated</td>
            </tr>
            <tr>
              <th>IMAGE</th>
              <th>ID</th>
              <th>NAME</th>
              <th>EMAIL</th>
              <th>CREATED</th>
              <th><!-- empty header for "View Profile" button --></th>
              <th><!-- empty header for "Delete User" button --></th>
            </tr>
          </thead>
          <tbody>
            <%= render @users %>
          </tbody>
        </table>
      </div><!-- /.table-responsive -->
    </div> <!-- /.panel.panel-default -->
    <div class="row">
      <div class="col-xs-12 text-center">
        <%= will_paginate @users, inner_window: 1, renderer: BootstrapPagination::Rails %>
      </div><!-- /.col-xs-12 -->
    </div><!--/.row -->
  </div><!-- /.col-md-12 -->
</div> <!-- /.row -->

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row">
  <div class="col-md-4">
    <h1>Sign Up</h1>
    <h3>It's free!</h3>
    <p>Get all of these benefits:</p>
    <ul>
      <li>Store your recipes online</li>
      <li>Keep recipes private or share them</li>
      <li>Read reviews of your recipes</li>
      <li>Review and save your favorite recipes</li>
    </ul>
  </div> <!-- /.col-md-4 -->
  <div class="col-md-8">
    <h1>Create Your Account</h1>
    <%= form_for(@user) do |f| %>
    
      <%= render 'shared/error_messages', object: f.object %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
      
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div> <!-- /.col-md-8 -->
</div> <!-- /.row -->

app/views/users/show.html.erb
<% provide(:title, @user.name + " User Profile") %>

<div class="row">
  <div class="col-xs-4 col-sm-3 col-md-2 col-md-offset-1">
    <%= image_tag(@user.image_url.url(:square), alt: @user.name + " Profile Image", class: "img-responsive profile-img") %>
  </div>
  <div class="col-xs-8">
    <h1><%= @user.name %></h1>
    <p>Member Since: <%= @creation_date %></p>
    <p>Location: <%= @user.location %></p>
    <% if current_user?(@user) %>
    <p><%= link_to "Edit Profile", edit_user_path, :class => "btn btn-primary", :role => "button" %></p>
    <% end %>
  </div>
</div> <!-- /.row -->

<hr/>

<div class="tab-display">
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><%= link_to("Recipes", "#user-recipes", aria: { controls: "user recipes" }, role: "tab", data: { toggle: "tab" }) %></li>
    <li role="presentation"><%= link_to("Reviews", "#user-reviews", aria: { controls: "user reviews" }, role: "tab", data: { toggle: "tab" }) %></li>
    <li role="presentation"><%= link_to("Favorites", "#user-favorites", aria: { controls: "user favorites"}, role: "tab", data: { toggle: "tab" }) %></li>
  </ul><!-- /.nav-tabs -->
  
  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="user-recipes">
      <%= render 'user_recipe_display' %>
    </div><!-- /#user-recipes -->
    <div role="tabpanel" class="tab-pane fade" id="user-reviews">
      <%= render 'user_review_display' %>
    </div><!-- /#user-reviews -->
    <div role="tabpanel" class="tab-pane fade" id="user-favorites">
      <%= render 'user_favorite_display' %>
    </div><!-- /#user-favorites -->
  </div><!-- /.tab-content -->
</div><!-- /.tab-display -->