config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  root 'collections#index'
  
  get 'about'     => 'static_pages#about'
  get 'privacy'   => 'static_pages#privacy'
  get 'terms'     => 'static_pages#terms'
  get 'signup'    => 'users#new'
  get 'login'     => 'sessions#new'
  post 'login'    => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :recipes do
    resources :reviews, only: [:index, :show]
    put :favorite, on: :member
    put :add_to_collection, on: :member
    collection do
      get 'popular'
      get 'latest'
      get 'quick'
      get 'admin_view'
    end
  end
  resources :reviews, only: [:create, :update, :destroy]
  resources :collections do
    put :remove_from_collection, on: :member
    collection do
      get 'admin_view'
    end
  end

end

app/views/layouts/_favicon.html.erb
<% %w(57 60 72 76 114 120 144 152 180).each do |size| %>
  <%= favicon_link_tag "apple-touch-icon-#{size}x#{size}.png", rel: 'apple-touch-icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

<% %w(16 32 96).each do |size| %>
  <%= favicon_link_tag "favicon-#{size}x#{size}.png", rel: 'icon', type: 'image/png', sizes: "#{size}x#{size}" %>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="mc">
  <div class="container">
    <ul class="footer-links">
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Privacy", privacy_path %></li>
      <li><%= link_to "Terms of Use", terms_path %></li>
      <li class="pull-right small"> 
        <%= link_to "http://jpkarlsven.com" do %>
          &copy; <%= " #{Date.current.year} J.Karlsven" %>
        <% end %>
      </li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header"> <!-- Brand and toggle button -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("makechow_logo.png", height: '50px'), root_path, class: "navbar-brand" %>
      </div> <!-- /.navbar-header -->
      
      <div class="collapse navbar-collapse" id="main-navbar-collapse">
        
        <ul class="nav navbar-nav">
          <li><%= link_to "Browse", { controller: "recipes", action: "index", sort_by: "Date" }  %></li>
        </ul>
        
        <%= form_tag recipes_path, :method => 'get', class: 'navbar-form navbar-left', role: 'search' do %>
          <div class="form-group">
              <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search Recipes' %>
              <%= button_tag(type: 'submit', class: 'btn btn-default', name: nil) do %>
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
              <% end %>
          </div>
        <% end %>
        
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= image_tag(current_user.image_url.url(:square), size: "50", alt: current_user.name, class: "img profile-img") %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Recipes", user_path(current_user, anchor: "user-recipes") %></li>
                <li><%= link_to "Favorites", user_path(current_user, anchor: "user-favorites") %></li>
                <li><%= link_to "Reviews", user_path(current_user, anchor: "user-reviews") %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Log out", logout_path, method: "delete" %></li>
              </ul>
            </li> <!-- /.dropdown -->
          <% else %>
            <li><%= link_to "Login", login_path %></li>
          <% end %>
        </ul>
        
        <% if logged_in? && current_user.admin? %>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle link-icon" data-toggle="dropdown">
                <span class="glyphicon glyphicon-wrench" aria-hidden="true"></span> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
                <li><%= link_to "Collections", admin_view_collections_path %></li>
                <li><%= link_to "Recipes", admin_view_recipes_path %></li>
              </ul>
            </li>
          </ul>
        <% end %>
        
      </div> <!-- /#main-navbar-collapse.collapse.navbar-collapse -->
    </div> <!-- /.container -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
<head>
  <title><%= yield(:title) %> | Make Chow | Top food, snack, and drink recipes on the web</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  <%= render 'layouts/favicon' %>
</head>
<body class="<%= controller_name %> <%= action_name %>">
  
  <div id="page-container">
  
    <%= render 'layouts/header' %>
  
    <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <% flash.each do |message_type, message| %>
              <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
            <% end %>
          </div><!-- /.col-xs-12 -->
        </div><!-- /.row -->
        <%= yield %>
      
        <% if Rails.env.development? %>
          <div class="row">
            <div class="col-md-8">
              <%= debug(params) %>
            </div>
          </div>
        <% end %>
    </div><!-- /.container -->
  
    <%= render 'layouts/footer' %>
  
  </div><!-- #page-container -->
  
</body>
</html>